version: '3.9'

services:

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1qaz
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
